### ISSUE TITLE
[Elden Ring Frame Data Explorer] "HasChanged" tag applied to all multi-hit attacks due to missing values in DamageLevel field

### ISSUE THREAD

**Issue by SenApollo** [sovietspaceship/souls-bug-reports#10]
**Application**

-   Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)

**Describe the incorrect or missing data**
All multi-hit attacks are missing DamageLevel values for attacks beyond the first in Regulation 1.09, causing these attacks to be flagged with the "HasChanged" tag incorrectly.

**Evidence**
Urumi 2hcR2 tagged with "HasChanged": 
![image](https://user-images.githubusercontent.com/111231548/228941162-91a54e94-4fa2-4ac4-99b4-a8815dfd385f.png)

DamageLevel field is the only difference, is missing information in 1.09:
![image (1)](https://user-images.githubusercontent.com/111231548/228941215-439b7125-3bbd-4d13-a092-174092c13a6a.png)

**Additional context**
I have not checked every attack in the tool, but can confirm this is at least the case for the 2h claw weapon attacks.

**Comment by sovietspaceship** [comment]
sorted
