### ISSUE TITLE
[Elden Ring Inventory Tool] Weapon upgrade level support

### ISSUE THREAD

**Issue by pomcomic** [sovietspaceship/souls-bug-reports#11]
**Application**

-   Elden Ring Inventory Tool (https://er-inventory.nyasu.business)

**Is your feature request related to a problem? Please describe.**
I'd love to be able to alter the weapon upgrade levels. I'm using many different rune levels for my builds and while I love the latest update that takes into consideration equipped talismans, displays damage numbers and so on, I'm a little bummed that the damage numbers on display always assume max weapon upgrades.

**Describe the solution you'd like**
I'd love a text input box (maybe in the stat overview window) that allows me to add the weapon upgrade level I want to go for. A dropdown menu for upgrade levels (regular and somber) would be fine too.

**Comment by sovietspaceship** [comment]
Much of the functionality is implemented but currently hidden as not finished, I plan to release it soon along with a multiplayer level range calculator as a textbox input. Somber upgrade is regular * 2/5

**Comment by pomcomic** [comment]
Awesome, looking forward to seeing it in action :)

**Comment by sovietspaceship** [comment]
done
