### ISSUE TITLE
[Elden Ring Inventory Tool] Support buffs

### ISSUE THREAD

**Issue by von-de** [sovietspaceship/souls-bug-reports#12]
**Application**

-   Elden Ring Inventory Tool (https://er-inventory.nyasu.business)

**Is your feature request related to a problem? Please describe.**
When trying to optimize for possible damage, there is something DS3's SoulsPlanner allowed you to do, that none of the ER planners I am aware of are capable of currently, that is to calculate how item buffs (greases or other consumable-based buffs) impact player stats or weapon stats. 

**Describe the solution you'd like**
An implementation akin to how DS3 SoulsPlanner (https://soulsplanner.com/darksouls3) has it; a check box next to the item allows to toggle the player/weapon stats with and without the buff enabled. 

**Describe alternatives you've considered**
Unfortunately, I do not know how else this could be implemented.

**Additional context**
Having this would allow players to optimize characters for weapon or player buffs without having to trial-and-error or to calculate scaling/AR differences separately.

**Comment by sovietspaceship** [comment]
good idea, I'll do this sometime

**Comment by sovietspaceship** [comment]
deployed
