### ISSUE TITLE
[Elden Ring Frame Data Explorer] Potentially mislabeled attack

### ISSUE THREAD

**Issue by nagleaidan** [sovietspaceship/souls-bug-reports#13]
**Application**

-   Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)

**Describe the bug**
Was double checking that no guard-counters were parriable and saw that 2h dagger/claw guard counter was marked as parriable. Checked the frame data (in the explorer) and saw that it had a `release to uncharged` speffect which seemed odd. Looked up the tae in DSAnim and it looks to be a 1h straight sword r2. Therefore, I think the attack is mislabeled in the FDE. Filename `a022_030510`

**To Reproduce**

1. Set `Type` to `Parriable`
2. Set `Attack` to `1h Guard Counter` and `2h Guard Counter`
3. Open the only result

**Screenshots**
![image](https://user-images.githubusercontent.com/15807611/232326850-2c65077a-6d2a-4fa7-9a50-a0193de96b52.png)
![image](https://user-images.githubusercontent.com/15807611/232327031-13dc0683-3b42-4a04-8480-909383fe4254.png)

**Comment by sovietspaceship** [comment]
yes that is some dagger R2, it was mislabelled in the original spreadsheet I used as data source, but I plan to use attackparam_pc instead in the near future

**Comment by nagleaidan** [comment]
Confirmed fixed in published version
