### ISSUE TITLE
[Elden Ring Frame Data Explorer] 

### ISSUE THREAD

**Issue by ZPacmanz** [sovietspaceship/souls-bug-reports#14]
**Application**

-   Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)

**Describe the incorrect or missing data**

**Evidence**
Screenshots or details from game data or other supporting tools

**Additional context**

**Comment by ZPacmanz** [comment]
Currently the curved sword feint data isnt labled or missing in the frame data tool
![image](https://user-images.githubusercontent.com/28971103/232491090-dc2bd5a2-33d4-485c-8f65-7c4c6ddb2987.png)

**Comment by sovietspaceship** [comment]
fixed
