### ISSUE TITLE
[Elden Ring Inventory Tool] Radagon's Soreseal doesn't change max HP or Equip Load

### ISSUE THREAD

**Issue by pomcomic** [sovietspaceship/souls-bug-reports#15]
**Application**

-   Elden Ring Inventory Tool (https://er-inventory.nyasu.business)

**Describe the bug**
Equipping Radagon's Soreseal does not change Equip Load nor HP properly

**To Reproduce**

1. Go to 'Talismans'
2. Click on an empty Talisman Slot
3. Equip Radagon's Soreseal
4. The +5 Vigor and +5 Endurance do not alter the Character's Equip Load or total HP anywhere

**Expected behavior**
For instance, I'd expect my character's HP to go from 1216HP at 35 Vigor to raise to 1450HP at 35+5 Vigor. The HP or Equip Load values do not change. However, weapon damage and requirements DO change properly. The wrong values are visible in the attached screenshot below.

**Screenshots**
![Bildschirm­foto 2023-05-08 um 11 12 02](https://user-images.githubusercontent.com/130552355/236785270-55c4655e-723a-4a44-9fe0-df494c9dc914.png)

**Comment by sovietspaceship** [comment]
fixed
