### ISSUE TITLE
[Elden Ring Inventory Tool] Request for a Two-Handing toggle

### ISSUE THREAD

**Issue by pomcomic** [sovietspaceship/souls-bug-reports#16]
**Application**

-   Elden Ring Inventory Tool (https://er-inventory.nyasu.business)

**Is your feature request related to a problem? Please describe.**
I'd love the addition of a two-hand toggle of sorts to display weapon AR values when they're being two-handed rather than only having access to the 1H damage values. Would be especially useful for STR builds.
Alternatively, the 1H and 2H values could be displayed by default on the weapon mouseover popups, though that wouldn't make sorting by 1H or 2H damage amount in the picker possible, which would also be rather nice.

**Describe the solution you'd like**
I'm kindly requesting adding a toggle to either the inventory manager or stat overview window (possibly both?) to swap between 1H and 2H damage values. 

**Describe alternatives you've considered**
Displaying both 1H and 2H AR values in the weapon mouseover popup could be an alternative to the toggle.

**Additional context**
eip.gg's build planner has this feature implemented, I think something similar would be a good addition to your build planner as well. 
![Bildschirm­foto 2023-05-08 um 11 21 54](https://user-images.githubusercontent.com/130552355/236787542-23add18c-c9f3-4c5d-b7ae-3d1c3479809d.png)

**Comment by sovietspaceship** [comment]
implemented and released
