### ISSUE TITLE
Elden Ring Inventory Tool Talismans Filter

### ISSUE THREAD

**Issue by Plexonator** [sovietspaceship/souls-bug-reports#17]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business), **Talismans**

**Is your feature request related to a problem? Please describe.**
When planning and adding talismans in the Inventory Tool, a lot of the talismans visible are inferior versions and scrolling past them to find what I am looking for slows me down by a whole second each time.

**Describe the solution you'd like**
A simple filter to only show the strongest version of each talisman.

**Describe alternatives you've considered**
I could stop being a baby and just scroll.

**Additional context**
Having the lower tier talismans there is important for planning lower level builds, if one wants to use appropriate talismans for early game. However, most people using these great tools are playing higher level (typically around meta), so a filter for showing the superlative talismans would be nice.
![firefox_XbBiS9AXK3](https://github.com/sovietspaceship/souls-bug-reports/assets/8589641/b46c0497-5316-46c1-944e-1692e0fe5e4f)

**Comment by sovietspaceship** [comment]
will do for next release

**Comment by sovietspaceship** [comment]
implemented
