### ISSUE TITLE
[Elden Ring Inventory Tool] Failed to load module script

### ISSUE THREAD

**Issue by Politary** [sovietspaceship/souls-bug-reports#18]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**
When I open build planner after PC restart or not using it for sime time, i get grey screen with this error. After reloading page, my talismans are cleared and I have to reload the save file.

**To Reproduce**

1. Go to https://er-build-planner.nyasu.business
2. See error

**Expected behavior**
Planner opens and talisman window isn't reset.

**Screenshots**
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/69177597/517413d5-045f-407d-8171-c8c92cdfec28)

**If User Interface issue**
-   Device: Desktop
-   Browser: Chrome 113.0.5672.93

**Comment by sovietspaceship** [comment]
fixed a while ago
