### ISSUE TITLE
[Elden Ring Frame Data Explorer] Filter cannot find offhand attack animations

### ISSUE THREAD

**Issue by nagleaidan** [sovietspaceship/souls-bug-reports#19]
**Application**

-   Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)

**Describe the bug**
Using the `Attack` filter doesn't work for offhand attacks ever since you did the label transition. Offhand attacks are labeled as `Offhand L1 #` while the filter searches for `Offhand #`.

**To Reproduce**

1. Use `Attack` filter to search for an offhand attack
2. Verify that no animations are shown
3. Clear the filter
4. Search for `offhand` using the main search
5. See that all the off animations are shown

**Expected behavior**
The filter to be able to display offhand animations correctly

**Screenshots**
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/15807611/ca61df25-a8b6-48dd-80a0-0cbf70db01ff)
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/15807611/6fcb481f-9a14-4b83-b3a9-4a93022a25b4)

**If User Interface issue**

-   Device: Windows 10
-   Browser: Google Chrome 114.0.5735.35 beta

**Additional context**
No errors or warnings thrown in dev console

**Comment by sovietspaceship** [comment]
actually fixed this sometime ago but forgor to push which caused it to not deploy xd

sorted

**Comment by nagleaidan** [comment]
classic
confirmed fixed
