### ISSUE TITLE
[Elden Ring Inventory Tool] 

### ISSUE THREAD

**Issue by janiekh** [sovietspaceship/souls-bug-reports#20]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Is your feature request related to a problem? Please describe.**
The defense numbers in the weapon damage calculator reset every time I check a new weapon. Meaning I constantly have to readjust the numbers if I'm checking for damage at lower levels.

**Describe the solution you'd like**
It would be nice if it either saved the numbers in session, in the build or let me make a preset.

**Describe alternatives you've considered**
If it took my build's defenses as the default every time that could work too.

**Additional context**
I just started using the build planner and it's amazing, thank you for all great work!

**Comment by sovietspaceship** [comment]
ready to deploy; values will be stored across sessions in browser-local storage

**Comment by sovietspaceship** [comment]
done
