### ISSUE TITLE
[Elden Ring Frame Data Explorer] Please bing back ToughnessParam values for hyperarmour

### ISSUE THREAD

**Issue by windias** [sovietspaceship/souls-bug-reports#21]
**Application**

-   Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)

**Describe the incorrect or missing data**
ToughnessParam values for hyperarmour not displayed

**Evidence**
Screenshots or details from game data or other supporting tools

**Additional context**

**Comment by sovietspaceship** [comment]
done
