### ISSUE TITLE
[Elden Ring Inventory Tool] 

### ISSUE THREAD

**Issue by Lily-Argyle** [sovietspaceship/souls-bug-reports#23]
on opera gx web browser
when i try to add any sort of bow or crossbow the picker menu goes blank
![image_2023-08-07_094553567](https://github.com/sovietspaceship/souls-bug-reports/assets/129092408/28678618-fdc1-4f37-807e-8f05e8ab97a9)

**Comment by sovietspaceship** [comment]
fixed
