### ISSUE TITLE
[Elden Ring Inventory Tool] Optimise protectors for multiple stats

### ISSUE THREAD

**Issue by lilyargylle** [sovietspaceship/souls-bug-reports#27]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

Would be cool if i could apple multiple fields(e.g.  Lightening damage and slash damage or poise and robustness) at the same time while optimising my armour. 
Or maybe even optimise it for a specific weapon with its respective stat allocation(e.g. 50int halberd) 

Thnx

**Comment by sovietspaceship** [comment]
done in a previous release
