### ISSUE TITLE
[Elden Ring Inventory Tool] Deleting multiples of one item deletes only some

### ISSUE THREAD

**Issue by roadrunnersf** [sovietspaceship/souls-bug-reports#3]
**Application**

-   Elden Ring Inventory Tool (https://er-inventory.nyasu.business)

**Describe the bug**
Deleting multiples of one item deletes some of them (seems to depend on which item you click before clicking 'Select All'

**To Reproduce**

1. Go to 'Weapon Planner'
2. With an empty inventory
3. Add 10 cleanrot knight swords with heavy infusion and an ash of war
4. Click the first sword in your inventory (to select it)
5. Click 'Select All'
6. Click 'Remove'
7. There are now 5 swords in your inventory when there should be 0

**Expected behavior**
All of the items are removed

-   Device: Desktop
-   Browser: Chrome Version 108.0.5359.126

**Comment by sovietspaceship** [comment]
Thank you for the report. Managed to reproduce and fix. Should be sorted now (commit ba66eaf)
