### ISSUE TITLE
Allow filtering by all affinities [Elden Ring Inventory Tool] 

### ISSUE THREAD

**Issue by chozandrias76** [sovietspaceship/souls-bug-reports#30]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Is your feature request related to a problem? Please describe.**
As a build maker
I would like to use less critical thinking to determine the optimal affinity
for any given weapon
Using specific stats

**Describe the solution you'd like**
I would like a system where I can click a button to include all infusions when I sort by damage

**Describe alternatives you've considered**
I usually use my knowledge to determine the best stat, and go back and forth between alternatives to see the difference

**Additional context**
<img width="343" alt="image" src="https://github.com/sovietspaceship/souls-bug-reports/assets/2087677/0658654b-2292-4947-b0de-d4c06015e579">

**Comment by sovietspaceship** [comment]
that's a good idea, will do for next release

**Comment by sovietspaceship** [comment]
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/100027345/08b131e1-9e6d-4098-85b4-9b0fbf0d918e)

Implemented. Please note this adds a lot of weapons to the list, so it might can be pretty slow depending on filtering options selected (a couple seconds at worst)
