### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v2.18.1] Tags / Tags not saving

### ISSUE THREAD

**Issue by MyDeathRay** [sovietspaceship/souls-bug-reports#31]
When selecting a tag it doesn't stay after selecting save. The tag gets removed and it will only display PvE. 

This doesn't happen on all the builds I've made, only a couple. I assume it has to do with the stat allocation. If this is not fixable no big deal, it's just a minor annoyance for me to not have the tags I want set on the builds

**Comment by sovietspaceship** [comment]
yeah this is caused by autodetection, which should keep manually set tags but currently isn't. I will make it preserve any manually entered tags

**Comment by sovietspaceship** [comment]
fixed
