### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.0] Can no longer login with Discord account

### ISSUE THREAD

**Issue by darkmoonofyomi** [sovietspaceship/souls-bug-reports#35]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**
When i have logged out, i can no longer login with my discord account now. Don´t matter if i use the QR-Code or try it with my login datas. Tested with browser microsoft edge and google chrome. 

I can login in the app on my smartphone. So it seems to be an issue with the regular web tool application.

**Screenshots**
 
If i  click an enter my Data this should be normal:

![image](https://github.com/sovietspaceship/souls-bug-reports/assets/164337808/ecebf60b-ff7d-43be-98eb-7c789f410142)

However you can see below, i am still not logged in:

![image](https://github.com/sovietspaceship/souls-bug-reports/assets/164337808/c0053134-8987-49cd-bd94-edc1e2f11449)

**Comment by sovietspaceship** [comment]
thanks a lot, should be fixed now
