### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.0] Damage Calculator / Dragon Towershield incorrect motion values

### ISSUE THREAD

**Issue by Zarden-Curtis** [sovietspaceship/souls-bug-reports#37]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the incorrect or missing data**
Dragon Towershield displays inflated damage for the 1h r1 1 because it treats the attack as a multi-hit attack with 3 hits

**Evidence**
![Screenshot 2024-03-27 130325](https://github.com/sovietspaceship/souls-bug-reports/assets/165166955/72168966-89ff-4d0c-befd-8f236a5a99bb)

**Additional context**
When sorting all weapons by damage, this shield will often show up near the top of the list due to this bug

**Comment by sovietspaceship** [comment]
done
