### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.2] Damage Calculator / Lance CR1 damage calculation is incorrect

### ISSUE THREAD

**Issue by DiscountSupport** [sovietspaceship/souls-bug-reports#38]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**

**To Reproduce**

1. Open the damage calculator for Lances

**Expected behavior**
Numbers are reasonable

**Screenshots**
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/127797047/6a3f60c1-fa73-4871-ad96-50e44784620e)

**If User Interface issue**

-   Device: Desktop 
-   Browser: Firefox

**Additional context**

**Comment by sovietspaceship** [comment]
this is a rykard boss fight moment (pve only damage events), will fix it next release

**Comment by sovietspaceship** [comment]
fixed
