### ISSUE TITLE
[Elden Ring Inventory Tool] Disable Frame Data button if multiple weapons are selected

### ISSUE THREAD

**Issue by roadrunnersf** [sovietspaceship/souls-bug-reports#4]
**Application**

-   Elden Ring Inventory Tool (https://er-inventory.nyasu.business)

**Describe the bug**
Selecting 3 weapons has the 'view frame data' button available when it should not be
**To Reproduce**

1. add 3 identical weapons (or not identical, don't think it matters)
2. select them all by clicking on them one at a time
3. Click 'view frame data'
4. nothing happens

This buttons should not be disabled, or (bonus), it should go to the frame data if all of the selected items have the same frame data (e.g. 3 identical weapons)

**Expected behavior**
The frame data button be disabled if it is available, or do something if that makes sense

**Comment by sovietspaceship** [comment]
Fixed in b623df7
