### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.2] Armour / Deleting a preset with the same name as another preset of the same category, deletes both

### ISSUE THREAD

**Issue by chozandrias76** [sovietspaceship/souls-bug-reports#41]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**
As a user who uses presets
I would like to overwrite presets by name
And only effect one preset when deleting that preset

**To Reproduce**

1. Create an armor layout
2. Save it as a preset
3. Update the armor layout
4. Save it as a preset with the same name
5. Delete the old preset

**Expected behavior**
Only one preset gets deleted, instead of both
OR
When saving a preset with the same name, the user is asked if they want to overwrite that preset

BONUS
Presets have the same name if the downcased version of it matches the downcased name of another preset of the same category

**Screenshots**
<img width="428" alt="image" src="https://github.com/sovietspaceship/souls-bug-reports/assets/2087677/82a246c4-925f-4aaf-9283-ff27df3d5e84">
<img width="482" alt="image" src="https://github.com/sovietspaceship/souls-bug-reports/assets/2087677/85cc9257-7c02-42e6-a7b8-d3854149e712">
<img width="335" alt="image" src="https://github.com/sovietspaceship/souls-bug-reports/assets/2087677/f051086a-d4fb-4b4b-8d0e-09fa1ad5da4f">
<img width="719" alt="image" src="https://github.com/sovietspaceship/souls-bug-reports/assets/2087677/a4385ec0-14f0-4484-be57-3ce025a9cc8e">

**Additional context**
Occurs with all forms of presets

**Comment by sovietspaceship** [comment]
fixed
