### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.2] Cheat Engine / Cannot read properties of undefined (reading 'full_hex'id')

### ISSUE THREAD

**Issue by chozandrias76** [sovietspaceship/souls-bug-reports#43]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**
As a user of the Cheat Table save
I would like to be able to export any generic save data using the existing feature
And for some information to result

**To Reproduce**

1. Go to https://er-inventory.nyasu.business/?b=a6902fb8804d04
2. Click on Load/Save
3. Scroll down to Cheat Engine
4. Click on Create Table

**Expected behavior**
A file download prompt appears

**Behavior**
None
```js
TypeError: Cannot read properties of undefined (reading 'full_hex_id')
    at sv (index-BvtkjDas.js:938:254)
    at f (index-BvtkjDas.js:1133:277)
    at u (index-BvtkjDas.js:1132:6450)
    at kl (index-BvtkjDas.js:19:38)
    at fn (index-BvtkjDas.js:19:109)
```
**Screenshots**
<img width="1810" alt="image" src="https://github.com/sovietspaceship/souls-bug-reports/assets/2087677/8098481f-9dde-4d9f-809d-56b89745b4d9">

**Additional context**
[Add any other context about the problem here.](https://er-inventory.nyasu.business/?b=a6902fb8804d04)
```js
function sv(t) {
    const e = yt()
      , i = ft()
      , a = e.weapons.get(t.name)
      , s = a.affinity[t.infusion]
      , r = e.ashesOfWar.get(t.weaponArt || c(a))
      , n = r ? r.full_hex_id.replace(/^2/, "8") : "FFFFFFFF"
      , o = t.upgrade == null ? i.current.character.weaponUpgrade : t.upgrade
      , l = C0(parseInt(s.full_hex_id, 16)); // THIS IS THE OFFENDING LINE
    return n0([l, C0(1), C0(o, 4) + "0000", n]) + ` // ${t.infusion} ${a.name} +${o} with ${(r == null ? void 0 : r.name) || "default"}`;
    function c(d) {
        if (d.allow_ash_of_war) {
            const u = Object.values(e.ashesOfWar.all).find(f=>f.skill_id === d.default_skill_id);
            return u ? u.name : null
        }
        return null
    }
}
```

**Comment by chozandrias76** [comment]
@sovietspaceship The issue goes away when I set the Ghostflame Torch to Standard Infusion. Maybe it is because I was only picking Heavy Weapons and that weapon included it, which is probably an invalid infusion. Maybe that is the easiest fix, but I also think an error message could be useful.

**Comment by chozandrias76** [comment]
As an aside, I don't think this torch should have any ash of war by default

**Comment by sovietspaceship** [comment]
fixed
