### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.2] Cheat Engine / Importing Spells using the generated CT should fill the expected slots

### ISSUE THREAD

**Issue by chozandrias76** [sovietspaceship/souls-bug-reports#44]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**

**To Reproduce**

1. Go to The Inventory Planner
2. Click on New Character
3. Scroll over to Spells
4. Add a spell in slot 0 and slot 1
5. Download the CT
6. Merge the CT along side TGA while the game is running
7. Click Equip Spells button
8. See that slot 0 occupies slot 1 and so on

**Expected behavior**
I expect slot 0 to be occupied if any spells are present, since the application does this

**Screenshots**
<img width="3840" alt="image" src="https://github.com/sovietspaceship/souls-bug-reports/assets/2087677/59f64f0a-259a-4998-a508-aefc700b50db">

**Additional context**
Should occur with any build that has spells

**Comment by sovietspaceship** [comment]
this is done with a separate script in the generated table, but i might add it to the spawning script as well

**Comment by sovietspaceship** [comment]
also the empty slot goes away as soon as you press next spell

**Comment by sovietspaceship** [comment]
implemented; waiting for the TGA table to release a fix as this is currently bugged on their end
