### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.3] Armour / Gravekeeper Cloak stats look wrong (fall damage, max damage, rune acquisition)

### ISSUE THREAD

**Issue by zeade** [sovietspaceship/souls-bug-reports#46]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the incorrect or missing data**

**Evidence**
Screenshots or details from game data or other supporting tools

**Additional context**

**Comment by sovietspaceship** [comment]
fixed
