### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.4] Armour Optimiser / Ragged Set

### ISSUE THREAD

**Issue by Zekeyo37** [sovietspaceship/souls-bug-reports#47]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**
Ragged set is listed as a full armor set to obtain, however it was patched out in 1.03.

**To Reproduce**

1: Go to armor
2: Search 'Ragged' 
3: Confirm it's in every armor slot option.

**Expected behavior**
I expect that since this set is patched out (1.03) and unobtainable, if someone were to use this online, they would be flagged for cheating and potentially penalized.

**Screenshots**

**If User Interface issue**

-   Device: Desktop or Mobile
-   Browser:

**Additional context**
I have not tested to see if an unobtainable set will result in a ban for obvious reasons, so I can only assume the worst.

P.S. if it's not a bannable/punishable offense to have unobtainble armor, then I'd be interested to know.

**Comment by sovietspaceship** [comment]
fixed
