### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.4] Save multiple specific setup for a build

### ISSUE THREAD

**Issue by caiohbe** [sovietspaceship/souls-bug-reports#48]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Is your feature request related to a problem? Please describe.**
It is a bit hard for me to remember all the equip load breakpoints of my builds, sometimes I think I can Equip a loadout without fat rolling but in reality I can't or I can be unsure of it.

**Describe the solution you'd like**
Having slots for a loadout means I can assign a set of armor, a set of talis, and a set of the equiped weapons to a "save slot". Being able to customize the name of the loadout would be really usefull too as I can make notes for myself and whoever see the build, for example:
"favor+jar psgs (raptor talons)", "jar psgs (offstoc)", "4talis psgs", "88P psgs"

**Describe alternatives you've considered**
An alternative for my solution would be the usage of the tag feature for agrouping these weapons/talis/armors

**Additional context**
Being able to create categories for it like folders would be usefull too, as I would be able to categorize per setup like: 
"psgs loadouts", "ts loadouts", "good MUs against sham(empty)", etc

**Comment by sovietspaceship** [comment]
this is already a feature
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/100027345/fb211f85-db94-4df1-a756-31e7a5b19ac2)

**Comment by sovietspaceship** [comment]
you can also use presets to make them reusable across different builds
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/100027345/9ff5bd85-f35d-4e0a-b957-fe0415af07fc)
