### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.6] Armour Optimiser suggests DLC content irrespective of DLC ownership setting

### ISSUE THREAD

**Issue by The-Albinobigfoot** [sovietspaceship/souls-bug-reports#49]
**Application**
-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**
As description.

**To Reproduce**
1. Disable SoTE in the settings.
2. Optimize armor with SoTE disabled and everything else set to default.
3. Optimizer suggests a set with the dlc headpiece "circlet of light"

**Expected behavior**
SoTE content should not appear in the suggested armor sets.

**Comment by sovietspaceship** [comment]
added in the next release
