### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.6.3] Cheat Engine / CE spawns +25 somber weapons

### ISSUE THREAD

**Issue by GusterTheShy** [sovietspaceship/souls-bug-reports#50]
**Application**

-   Elden Ring Build Planner / Inventory Tool (https://er-build-planner.nyasu.business)

**Describe the bug**
After doing the steps and chooseing "print inventory", all weapons, shields, seals etc. spawn as +25, even the somber ones.

**To Reproduce**
Generate script and copy into "print inventory", then start.

**Expected behavior**
I expected for everything to have correct upgrade.

**Screenshots**

![20240629081102_1](https://github.com/sovietspaceship/souls-bug-reports/assets/147542945/97d15f06-2d67-487f-af28-5526ad83d461)
![20240629081114_1](https://github.com/sovietspaceship/souls-bug-reports/assets/147542945/63ed9e09-93c3-4ddf-99b9-ddf557ab14f6)
![20240629081127_1](https://github.com/sovietspaceship/souls-bug-reports/assets/147542945/c9654db1-cf19-4f32-9f84-ac757fcce3a1)

**Additional context**

**Comment by sovietspaceship** [comment]
which tga version were you using?

**Comment by sovietspaceship** [comment]
this happens with the tga 1.11.0 table which had a fix released; please use the latest version (1.11.2) of the table and discard these items, it's very unlikely to be a ban risk but we don't know for sure yet

**Comment by sovietspaceship** [comment]
it will now prevent this from happening when using the affected tga table versions; please use 1.11.2 or newer
