### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.6.5] Armour / Different damage type order

### ISSUE THREAD

**Issue by Bobastic** [sovietspaceship/souls-bug-reports#52]
### Describe the bug

Not really a "bug" but damage types are not in the same order between Armor Optimizer and the Equipment tab.

### To Reproduce

Go to the Armor tab. Open the Armor Optimzer. On the left of the screen you see
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/63102199/c537dd80-4478-4059-a536-148c786099d5)
and on the right you see 
![image](https://github.com/sovietspaceship/souls-bug-reports/assets/63102199/d1ce2902-c480-48c6-8592-4b55c95592a6)

### Expected behavior

Same order as in game I guess?

### Device

Desktop

### Browser

Firefox

**Comment by sovietspaceship** [comment]
done
