### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.6.5] Damage Calculator / Damage Calculator doesn't display anything for Fireknight GS

### ISSUE THREAD

**Issue by JorgePereira09005** [sovietspaceship/souls-bug-reports#53]
### Describe the bug

Exactly what it sounds like. This is what it shows: 
![imagem](https://github.com/sovietspaceship/souls-bug-reports/assets/61985975/668fda4b-20cd-4edd-9e83-bf7b8dcb3a48)

### To Reproduce

Nothing special, seems to be broken on every build.

### Expected behavior

Numbers!

### Build or workspace URL

Consistently broken on every build.

### Device

Desktop.

### Browser

Firefox

**Comment by sovietspaceship** [comment]
fixed
