### ISSUE TITLE
[Elden Ring Frame Data Explorer] [v3.1.1] Frame data from previous patches for comparison.

### ISSUE THREAD

**Issue by Arthurice47** [sovietspaceship/souls-bug-reports#55]
**Application**

-   Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)

**Is your feature request related to a problem? Please describe.**
I am unsure how to properly word this, but I feel as though the most recent patch may have changed the frame data of certain attacks, such as Spinning Slash, without properly addressing so in the patch notes, and would like to verify if this is the case.

**Describe the solution you'd like**
The list of patches available in the top left of the tool only contains the most recent patch, 1.12.3 and the second most recent patch, 1.12, and it would be appreciated it any data for patch 1.10 or earlier was made available to view by selecting it from this list.

**Describe alternatives you've considered**
I've attempted to search for any frame data from previous patches for what I specifically want answered to no avail, there are no concise and detailed breakdowns of specific weapons and their unique frame data, such as the unique variation of Spinning Slash available on to the Dragon Halberd.

**Additional context**
I feel as though losing access to the frame data of previous patch notes is problematic in ways that extend beyond my current issue, as losing access to this data makes it hard for anyone to identify when something has changed with recent game updates in comparison to previous ones, as the previous point of comparison is no longer available in an easy and concise way to actually compare with.

**Comment by sovietspaceship** [comment]
1.10 is still there in the regulation dropdown, previous versions have been removed because each adds several minutes to build time everytime I need to update the app.

are you on firefox? there's is a firefox bug that doesn't display the last entry in a dropdown, which might be why you can't see 1.10 in the list
