### ISSUE TITLE
[Elden Ring Frame Data Explorer] [v3.1.1] Fire Knight's Greatsword Missing 2h R1 1/2/3 Data

### ISSUE THREAD

**Issue by jackmeagher** [sovietspaceship/souls-bug-reports#56]
The Fire Knight's Greatsword 2h R1 1/2/3 moves are all listed as "special", and then display nothing.

**Comment by jackmeagher** [comment]
![Screenshot 2024-07-18 125427](https://github.com/user-attachments/assets/c97b96b9-d289-4f3d-9b58-1e512042870c)

**Comment by sovietspaceship** [comment]
yeah this happens because they're cloned animations, and i forgor to run the exporter to get an updated list of those; will fix next release

**Comment by sovietspaceship** [comment]
fixed
