### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.7] Damage Calculator / Fire Knight's Greatsword has bugged damage calculations

### ISSUE THREAD

**Issue by Owlvard** [sovietspaceship/souls-bug-reports#57]
### Describe the bug

All damage calculations give 0.
The whole damage calculator doesn't show up.

### To Reproduce

1. Select fire Knight's greatsword in the weapons tab
2. Select the Damage calculator from the drop down.

### Expected behavior

visible damage calc

### Screenshots

![image](https://github.com/user-attachments/assets/f425fbdc-1be7-4c26-8bb8-df3a59abc07f)
![image](https://github.com/user-attachments/assets/b7cd8dc8-9c00-453c-a6f2-4d8aab753008)

### Device

Desktop

### Browser

Chrome

**Comment by sovietspaceship** [comment]
related to https://github.com/sovietspaceship/souls-bug-reports/issues/56

**Comment by sovietspaceship** [comment]
fixed
