### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.7] Effects / Missing Golden Vow (Tool) on consumable effects list

### ISSUE THREAD

**Issue by CarianSoviet** [sovietspaceship/souls-bug-reports#58]
### Describe the incorrect or missing data

In the Overview, on the "Use consumable" list, there is no "Golden Vow" item introduced in the DLC

### Evidence

![image](https://github.com/user-attachments/assets/0d29cbd9-4b5b-483a-b8c8-9d8d1c468381)

**Comment by CarianSoviet** [comment]
I'm using this planner for the first time... so if i'm just searching on the wrong place sorry

**Comment by sovietspaceship** [comment]
yeah not all consumable effects are in the app, I'm adding more with each update, probably adding this one next

**Comment by CarianSoviet** [comment]
oh i see, thanks a lot!! Great work with the planner btw
