### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.7.1] Talismans / host's trick-mirror missing from talismans

### ISSUE THREAD

**Issue by ssspons** [sovietspaceship/souls-bug-reports#59]
### Describe the bug

Only the furled-finger's trick-mirror shows up in the talismans tab.

### Screenshots

![where other mirror](https://github.com/user-attachments/assets/1e433c54-4945-4040-8efe-ada2575e622a)

### Device

Desktop

### Browser

Chrome

**Comment by sovietspaceship** [comment]
it's classed as non-pvp talisman atm, so it will only show if you turn off the pvp filter below

**Comment by sovietspaceship** [comment]
sorted
