### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.7.2] Scadutree blessing

### ISSUE THREAD

**Issue by S-202** [sovietspaceship/souls-bug-reports#60]
### Is your feature request related to a problem? Please describe.

Its a problem when i want to make a build for the DLC but i cant seem to find a way to implement scadutree blessing.

### Describe the solution you'd like

I want there to be a way to add scautree blessing to builds

**Comment by sovietspaceship** [comment]
this is currently implemented in the DLC Calculator (Search -> DLC Calculator), but the values aren't yet integrated in the rest of the app; might do for next release

**Comment by sovietspaceship** [comment]
done (enable PvE mode, can be toggled on and off with the Shadow Realm button that appears)
