### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.7.3] Cheat Engine / Setup Character Script not working

### ISSUE THREAD

**Issue by Ompolar** [sovietspaceship/souls-bug-reports#61]
### Describe the bug

Simply not giving any flasks and unlocking stuff
it appears to be giving some script not found :
1337193276
1337256125
1337258899
1337258901
1337258900
1337215543
1337192510
1337218242
1337193285
1337196796
1337197125
1337182512

### To Reproduce

1. TGA table with a copy of my character's generated table
2. enabling "Setup Character"
3. Errors happen

### Expected behavior

It should unlock maps, flasks, grace, colloseum, summoning pool, cookbooks and whetblades

### Device

Desktop

### Browser

Chrome

**Comment by sovietspaceship** [comment]
tga table updated, please use the supported version for now (1.13.0)

**Comment by Ompolar** [comment]
> tga table updated, please use the supported version for now (1.13.0)

I forgot to put tga version, and it was already the latest version of it
maybe it was on my end..

**Comment by lndura** [comment]
Moat recent table from TGA is app_ver 1.13.0, which refers to the Elden ring version. 

The most recent TGA table is on table_ver 1.15.0, but you'll have to use table_ver 1.13.0 to be able to use the planner untill Emillia upates it :catbox:

**Comment by Ompolar** [comment]
> Moat recent table from TGA is app_ver 1.13.0, which refers to the Elden ring version.
> 
> The most recent TGA table is on table_ver 1.15.0, but you'll have to use table_ver 1.13.0 to be able to use the planner untill Emillia upates it :catbox:

whoops sorry, im bad at reading -/\- thankyou indura

**Comment by sovietspaceship** [comment]
sorted
