### ISSUE TITLE
[Elden Ring Frame Data Explorer] [v3.1.4] Frame Data / Colossal Weapons like Duelist Greataxe missing crouch r1 data

### ISSUE THREAD

**Issue by hazylua** [sovietspaceship/souls-bug-reports#62]
**Application**

-   Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)

**Describe the incorrect or missing data**
Tried to search for frame data info on Colossal Weapons 2h/1h crouch r1 and it doesn't show up. Seems to be missing.

**Evidence**
Screenshots or details from game data or other supporting tools.
![image](https://github.com/user-attachments/assets/43540e50-7140-487c-9da1-9a9aa5a76896)

****If applicable, provide the URL of your build or workspace that displays the issue.***
https://er-frame-data.nyasu.business/?a=2h+Crouch+R1&w=Bloodfiend%27s+Arm&w=Duelist+Greataxe&w=Zweihander

**Additional context**
Just simple search of framedata.

**Comment by sovietspaceship** [comment]
crouch is a separate animation only for certain weapons, generally crouch uses the rolling attack animation which is the case for colossal weapons as well. maybe i'll add something in the future to make this visible in the app
