### ISSUE TITLE
[Elden Ring Build & Inventory Planner] [v3.7.7] "secondary" weapon tag

### ISSUE THREAD

**Issue by Eyl-fr** [sovietspaceship/souls-bug-reports#65]
### Is your feature request related to a problem? Please describe.

If I take **jar canon** in my build for example the requirement will be very high, on non-strength build the requirement ar not as hight as the **jar canon** or **stone wall shield**.
Same thing for maximum weight.  

### Describe the solution you'd like

These kinds of weapons are "tools" and are not being considered when we are making build, it can be cool if we ad some kind of tags that make the weapon "invisible" for the requirement or heaviest weapon for example.

a simple change that could make **stat perfect build** easier :)

### Describe alternatives you've considered

if not a tag then maybe a option when editing the weapon.

### Additional context

Just want to say thank you for all of this, you are helping the community so much !

Lot of love from the French pvp community !

**Comment by sovietspaceship** [comment]
![image](https://github.com/user-attachments/assets/8c0e4ecf-c3f6-4e56-abab-58e163ebe7e4)
done
