### ISSUE TITLE
[Elden Ring Inventory Tool] Cannot load inventory by url on first visit

### ISSUE THREAD

**Issue by roadrunnersf** [sovietspaceship/souls-bug-reports#8]
**Application**

-   Elden Ring Inventory Tool (https://er-inventory.nyasu.business)

**Describe the bug**
Opening an inventory URL in an incognito tab shows everything as empty
**To Reproduce**

1. Open an incognito tab in chrome
2. Go to an inventory URL e.g. [this](https://er-inventory.nyasu.business/?b=680e04075b4223).
3. The inventory is empty (if I reload the page, it loads with the expected talismans)

![image](https://user-images.githubusercontent.com/47029514/224156119-a59595b4-2f67-4cfc-b716-84da4fdda910.png)

**Expected behavior**
I expect to be able to load other people's URLs, having not visited the site before (empty local storage, might be linked to the bug)

**If User Interface issue**

-   Device: Desktop 
-   Browser: Chrome  Version 110.0.5481.180 (Official Build) (64-bit)

**Comment by sovietspaceship** [comment]
This should happen anytime you visit the app the first time and loading the inventory, which likely affects any user clicking on a shared link and have never visited it. Caused by not having authenticated with the server beforehand so yes empty localstorage with no session is the reason

**Comment by sovietspaceship** [comment]
fixed
