### ISSUE TITLE
[Elden Ring Frame Data Explorer] Fist 2H Running R2 damageLevel increase

### ISSUE THREAD

**Issue by GGiantDad** [sovietspaceship/souls-bug-reports#9]
**Application**

-   Elden Ring Frame Data Explorer (https://er-frame-data.nyasu.business)

**Describe the incorrect or missing data**
After Patch 1.09 the hitstun for the Fists 2H Running R2 was reduced, but the DamageLevel is reported to have been increased. In 1.08 is level 2, but in 1.09 is level 3, meaning more stunned frames before one could roll out.

**Evidence**
Screenshots or details from game data or other supporting tools
![image](https://user-images.githubusercontent.com/128826020/227562464-a36ec4bd-2a54-4789-908d-b9a079e69ef2.png)

**Additional context**
Prior to Patch 1.09, a 2H running R2 could be combo'ed into a 2H R2. Now it's not the case anymore, so it makes no sense that the DamageLevel was increased in the data of 1.09.

**Comment by sovietspaceship** [comment]
It has indeed increased, see https://docs.google.com/spreadsheets/d/1j4bpTbsnp5Xsgw9TP2xv6d8R4qk0ErpE9r_5LGIDraU/edit, unless I'm missing something

**Comment by GGiantDad** [comment]
Wow, that's so strange.

Unless I'm misinterpreting the data, if you nerf the hitstun, it should
show less frames, not more. Right?

Because you can't combo running R2 into R2 with fists anymore.




Em sex., 24 de mar. de 2023 às 12:19, Emilia ***@***.***>
escreveu:

**Comment by sovietspaceship** [comment]
It's been found that the damage levels for pvp do not map directly to the regular values; 3 maps to 1 in this case. Will update now with the full mapping

**Comment by sovietspaceship** [comment]
sorted
